Resources:
  table8235A42E:
    Type: AWS::DynamoDB::Table
    Properties:
      KeySchema:
        - AttributeName: siteName
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: siteName
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: skimlinks-siteid
    Metadata:
      aws:cdk:path: exit-proxy-dev/table/Resource
  redirectlambdaServiceRoleFA4625DB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: exit-proxy-dev/redirect-lambda/ServiceRole/Resource
  redirectlambdaServiceRoleDefaultPolicy6C0431B3:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:Scan
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - table8235A42E
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: redirectlambdaServiceRoleDefaultPolicy6C0431B3
      Roles:
        - Ref: redirectlambdaServiceRoleFA4625DB
    Metadata:
      aws:cdk:path: exit-proxy-dev/redirect-lambda/ServiceRole/DefaultPolicy/Resource
  redirectlambdaB95A9883:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: redirectlambdaCodeS3BucketB0F65FFC
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: redirectlambdaCodeS3VersionKey2E51E3D5
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: redirectlambdaCodeS3VersionKey2E51E3D5
      Handler: handlers/redirect.handler
      Role:
        Fn::GetAtt:
          - redirectlambdaServiceRoleFA4625DB
          - Arn
      Runtime: nodejs8.10
      Environment:
        Variables:
          SITE_ID_TABLE:
            Ref: table8235A42E
      MemorySize: 256
      Timeout: 5
    DependsOn:
      - redirectlambdaServiceRoleDefaultPolicy6C0431B3
      - redirectlambdaServiceRoleFA4625DB
    Metadata:
      aws:cdk:path: exit-proxy-dev/redirect-lambda/Resource
      aws:asset:path: asset.1412538e323f520b9145081e149cf4b1483cdeee29d1c9da088db311aaf23d53
      aws:asset:property: Code
  redirectlambdaApiPermissionGETexitToRetailer815D2446:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - redirectlambdaB95A9883
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-west-1:928536309678:"
            - Ref: exitproxyapi5B88BAD7
            - /
            - Ref: exitproxyapiDeploymentStageprod512D0D4E
            - /GET/exitToRetailer
    Metadata:
      aws:cdk:path: exit-proxy-dev/redirect-lambda/ApiPermission.GET..exitToRetailer
  redirectlambdaApiPermissionTestGETexitToRetailerC7B8B125:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - redirectlambdaB95A9883
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:eu-west-1:928536309678:"
            - Ref: exitproxyapi5B88BAD7
            - /test-invoke-stage/GET/exitToRetailer
    Metadata:
      aws:cdk:path: exit-proxy-dev/redirect-lambda/ApiPermission.Test.GET..exitToRetailer
  exitproxyapi5B88BAD7:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: exit-proxy-api
    Metadata:
      aws:cdk:path: exit-proxy-dev/exit-proxy-api/Resource
  exitproxyapiDeployment58D465E2e787bb09ba1b3c9f1e34a9e485b399fe:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: exitproxyapi5B88BAD7
      Description: Automatically created by the RestApi construct
    DependsOn:
      - exitproxyapiexitToRetailerGETDA80008F
      - exitproxyapiexitToRetailer66A0E400
    Metadata:
      aws:cdk:path: exit-proxy-dev/exit-proxy-api/Deployment/Resource
  exitproxyapiDeploymentStageprod512D0D4E:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: exitproxyapi5B88BAD7
      DeploymentId:
        Ref: exitproxyapiDeployment58D465E2e787bb09ba1b3c9f1e34a9e485b399fe
      StageName: prod
    Metadata:
      aws:cdk:path: exit-proxy-dev/exit-proxy-api/DeploymentStage.prod/Resource
  exitproxyapiCloudWatchRole298EEEEC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                Fn::Join:
                  - ""
                  - - apigateway.
                    - Ref: AWS::URLSuffix
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: exit-proxy-dev/exit-proxy-api/CloudWatchRole/Resource
  exitproxyapiAccount782CAEDE:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - exitproxyapiCloudWatchRole298EEEEC
          - Arn
    DependsOn:
      - exitproxyapi5B88BAD7
    Metadata:
      aws:cdk:path: exit-proxy-dev/exit-proxy-api/Account
  exitproxyapiexitToRetailer66A0E400:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - exitproxyapi5B88BAD7
          - RootResourceId
      PathPart: exitToRetailer
      RestApiId:
        Ref: exitproxyapi5B88BAD7
    Metadata:
      aws:cdk:path: exit-proxy-dev/exit-proxy-api/Default/exitToRetailer/Resource
  exitproxyapiexitToRetailerGETDA80008F:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: exitproxyapiexitToRetailer66A0E400
      RestApiId:
        Ref: exitproxyapi5B88BAD7
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :apigateway:eu-west-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - redirectlambdaB95A9883
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: exit-proxy-dev/exit-proxy-api/Default/exitToRetailer/GET/Resource
  domainname:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: exit.dotter-dev.me
      CertificateArn: arn:aws:acm:us-east-1:928536309678:certificate/bd8fb946-f396-415e-bf9a-abe3a7a45d31
    Metadata:
      aws:cdk:path: exit-proxy-dev/domain-name
  basepathmapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: exit.dotter-dev.me
      RestApiId:
        Ref: exitproxyapi5B88BAD7
      Stage: prod
    Metadata:
      aws:cdk:path: exit-proxy-dev/base-path-mapping
  recordset:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: exit.dotter-dev.me
      Type: A
      AliasTarget:
        DNSName:
          Fn::GetAtt:
            - domainname
            - DistributionDomainName
        HostedZoneId:
          Fn::GetAtt:
            - domainname
            - DistributionHostedZoneId
      HostedZoneId: Z3O3Q2CPUGBU7F
    Metadata:
      aws:cdk:path: exit-proxy-dev/record-set
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.34.0,@aws-cdk/assets=0.34.0,@aws-cdk/aws-apigateway=0.34.0,@aws-cdk/aws-applicationautoscaling=0.34.0,@aws-cdk/aws-autoscaling-common=0.34.0,@aws-cdk/aws-cloudwatch=0.34.0,@aws-cdk/aws-dynamodb=0.34.0,@aws-cdk/aws-ec2=0.34.0,@aws-cdk/aws-events=0.34.0,@aws-cdk/aws-iam=0.34.0,@aws-cdk/aws-kms=0.34.0,@aws-cdk/aws-lambda=0.34.0,@aws-cdk/aws-route53=0.34.0,@aws-cdk/aws-s3=0.34.0,@aws-cdk/aws-sqs=0.34.0,@aws-cdk/cdk=0.34.0,@aws-cdk/cx-api=0.34.0,@aws-cdk/region-info=0.34.0,jsii-runtime=node.js/v8.15.0
Parameters:
  redirectlambdaCodeS3BucketB0F65FFC:
    Type: String
    Description: S3 bucket for asset "exit-proxy-dev/redirect-lambda/Code"
  redirectlambdaCodeS3VersionKey2E51E3D5:
    Type: String
    Description: S3 key for asset version "exit-proxy-dev/redirect-lambda/Code"
  redirectlambdaCodeArtifactHashE0F3D010:
    Type: String
    Description: Artifact hash for asset "exit-proxy-dev/redirect-lambda/Code"
Outputs:
  exitproxyapiEndpointF0241CAB:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: exitproxyapi5B88BAD7
          - .execute-api.eu-west-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: exitproxyapiDeploymentStageprod512D0D4E
          - /

